name: Build LaTeX documents

on: 
  push:
    branches: ['main']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: ghcr.io/xu-cheng/texlive-full:latest
    
    steps:
      - name: update git
        run: |
          apk add --no-cache git

      - uses: actions/checkout@v2
      
      - name: build lectures
        run: |
          srcdir=lectures
          for dir in src/$srcdir/*/; do
            if [ ! -f "$dir"*.tex ]; then
              continue
            fi
            cd "$dir"
            for file in *.tex; do
              latexmk -lualatex -file-line-error -halt-on-error -interaction=nonstopmode -outdir=../../out/$srcdir "$file"
            done
            cd ../../..
          done

      - name: add dir to temporary safe
        run: |
          git config --global --add safe.directory /__w/MaM_Inno_2023/MaM_Inno_2023
        
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'out'
          author_name: 'GitHub Actions'
          commit: --signoff
          committer_name: 'Oleg Bulichev'
          message: '[auto-ci] added generated pdf'
          pathspec_error_handling: exitImmediately
          